### PR TITLE
Add public mem-test for latency testing

### PR DESCRIPTION
**Pull request by kayeoc279**
add submodule under software directory & update wit manifest as well
mem-test expected to release along with 19.11 release and 
it only works with linker script file generated by freedom-devicetree-tools with commit eba4dcd

please help to review & comment thx

### CODE REVIEW

**Comment by virtualboots** [comment]
Hi @bsousi5 and @nategraff-sifive ,
This PR is planned to be released in 19.11, but we don't know which branch to merge into, so we choose master. Is it correct? Please advise.

**Comment by nategraff-sifive** [comment]
Also, it looks like using `__max_heap` on the HiFive Unleashed is causing a relocation error. I think we need to be a bit more nuanced about how we max out the heap.

**Comment by nategraff-sifive** [comment]
Make sure you bump the freedom-devicetree-tools pointer to pick up the change which fixes `__max_heap`, right now it looks like this just contains the generated linker scripts but not the version of devicetree tools which creates them.

**Comment by kayeoc279** [comment]
Changing submodule freedom-device-tree tool commit to 9ed8270ffe0a (master)
linker script & parameterizing ocd file are generated base on commit mentioned above.

Let me know if there is other issue. Thx

**Comment by kayeoc279** [comment]
@bsousi5 
Thx for your comment, fix following things as you mentioned
- change benchmark-mem-test repo name to benchmark-mem-latency
- submodule name change to mem-latency
- Fix mem-latency README.md unaligned PROGRAM value
- use Freedom-metal get-cycle API
- Fix mem-latency description in README.md and doc/sphinx/contents.rst

Let me know if there is other issue. Thx

**Pull request merged**
