### PR TITLE
FreeRTOS

### PR DESCRIPTION
**Pull request by dbarbi1**
this PR changes the prints in _init to %ld to fix the compilation warning. Everything else is new to support FreeRTOS

### CODE REVIEW

**Comment by mwachs5** [comment]
Doesn't the %ld depend on whether you are compiling for 64 or 32 bit? @palmer-dabbelt?

**Comment by palmer-dabbelt** [comment]
On RV32 long is 32 bits, and on RV64 long is 64 bits.  You might want something like PRId64.

**Comment by dbarbi1** [comment]
this was generating a warning for me in the FreeRTOS builds. Now checking the standard sdk demos, i'm not seeing the warning when using the %d init file....

Is it possible my build arguments are missing something or incorrect?

**Comment by dbarbi1** [comment]
get_cpu_freq returns an unsigned long though, shouldn't we be using %ld?

**Comment by palmer-dabbelt** [comment]
If you're trying to print an unsigned long then you should use "%lu".

**Comment by dbarbi1** [comment]
Closing request. We are going to put FreeRTOS into it's own repo outside of FESDK

**Pull request closed without merging**
