### PR TITLE
adding new 'list-*-info' targets

### PR DESCRIPTION
**Pull request by cgsfv**
Update to the adding of manually managed meta information that Freedom Studio can use to ensure the best possible out-of-box experience when create new example software projects.

### CODE REVIEW

**Comment by cgsfv** [comment]
Any idea why the checks failed?

**Comment by nategraff-sifive** [comment]
> Any idea why the checks failed?

```
2020-11-04T18:06:31.2912213Z scripts/simulate --elf /freedom-e-sdk/software/hello/debug/hello.elf --qemu qemu-system-riscv64 --qemu-config bsp/qemu-sifive-s51/qemu.cfg
2020-11-04T18:06:31.2925401Z Launching QEMU! Press Ctrl-A, X to exit
2020-11-04T18:06:31.6067859Z ##[error]Process completed with exit code 124.
```

Exit code 124 means that `timeout` killed QEMU for running too long (more than 10 seconds) which most likely means that there's a mismatch between the elf built and the configuration of QEMU trying to run it.

There are quite a lot of changes to the Makefiles in this PR, so without digging further it's hard to say why the build is failing.

**Comment by cgsfv** [comment]
I didn't change anything related to SW build or QEMU launch, and it's running fine on my computer.
Could it be a glitch?
Is it possible to restart the checks?

**Comment by cgsfv** [comment]
Thanks for running the checks again.
Now it seems to fail with exit code 124 in another place.
What could possibly cause this?

**Comment by nategraff-sifive** [comment]
Timed out again after restarting the checks.

**Comment by nategraff-sifive** [comment]
> What could possibly cause this?

Hmm, maybe a QEMU version mismatch?

**Comment by cgsfv** [comment]
Don't know - I haven't changed anything that has to do with QEMU?

**Comment by cgsfv** [comment]
Maybe you could try to run the checks on master branch, just to see if that works OK?

**Comment by cgsfv** [comment]
I tracked it down to these lines in standalone.mk that made the checks fail - any idea why - doesn't it look quite straightforward?
`.PHONY: list-all-info`
`list-all-info:`
`	@echo e-sdk-tags: $(E_SDK_TAGS)`
`	@echo e-sdk-reqs: $(E_SDK_REQS)`
`	@echo riscv-arch: $(RISCV_ARCH)`
`	@echo target-tags: $(TARGET_TAGS)`
`	@echo riscv-reqs: $(RISCV_REQS)`
`	@echo program-tags: $(PROGRAM_TAGS)`

**Comment by nategraff-sifive** [comment]
I have no idea why that rule would break the build, unfortunately. Maybe somehow the `list-all-info` target was a prereq for some build intermediate and the fact that it was marked `.PHONY` meant something was getting rebuilt, but incorrectly somehow?

**Review by nategraff-sifive — APPROVED** [review]

**Comment by cgsfv** [comment]
I renamed the list-all-info to list-standalone-info, which seems to make it work.

**Review by nategraff-sifive — APPROVED** [review]

**Review by sifivekevin — APPROVED** [review]
LGTM

**Pull request merged**
