### PR TITLE
Enable FPU in MSTATUS CSR during init

### PR DESCRIPTION
**Pull request by scottj97**
This way, chips with FPU can run FPU instructions without taking
exceptions.

I've confirmed that dhrystone still runs successfully even on chips
with no FPU.

### CODE REVIEW

**Comment by mwachs5** [comment]
Do we need to do something in the Makefile to take advantage of this?

**Comment by scottj97** [comment]
No changes needed to Makefiles for init.c. For testfloat I've added the appropriate -march* options to use FPU instructions.

Conceivably we could make a different bsp for Fava vs Guava that would turn on the right GCC options when compiling for Fava. (Is it possible to do that via a bsp?)

**Comment by mwachs5** [comment]
@aswaterman gave me a code snippet that would basically do this and some other setup that would be required if you had an FPU:

```
li t0, MSTATUS_FS
csrs mstatus, t0
csrr t1, mstatus
and t1, t1, t0
beqz t1, 1f
fsrr x0
1:
```

**Comment by aswaterman** [comment]
That last instruction should be "fssr x0"--evidently I didn't try to assemble before sending that code.

The other option is to do what @scottj97 said and use ifdef __riscv_flen to prevent the code from being emitted when -march=RV32IMAC, rather than RV32IMAFC.  Should be OK either way.

**Comment by scottj97** [comment]
I pushed another commit that now checks MISA to see if the F extension is present, and also initializes the rounding modes (which are undefined at reset).

**Comment by aswaterman** [comment]
yep lgtm

**Pull request merged**
