### PR TITLE
Add SiFive HiFive Unmatched platform

### PR DESCRIPTION
**Pull request by zongbox**
This PR contains two commit,
- Add unmatched in bsp 
- Bumping related submodules
  - freedom-devicetree-tools
  - freedom-metal
  - devicetree-overlay-generator

### CODE REVIEW

**Comment by zongbox** [comment]
Changed in v2:
 - update submodule of freedom-metal to include this fix:  https://github.com/sifive/freedom-metal/commit/e9ad5f83ff60be96f262a371873b6ccff1f6e9fd
 This patch is needed for fixing the issue about Unmatched conflict with ccache initialization

**Comment by paul-walmsley-sifive** [comment]
Hi @zongbox , could you take a look at the CI test failures?  Looks like there's an issue with the devicetree-overlay-generator:

TypeError: set_rams() missing 1 required positional argument: 'region'

**Comment by zongbox** [comment]
@paul-walmsley-sifive Could you please help me to review and merge the following PR if it is good enough to you, and I would update this PR to include it. Thanks in advance.

In my original implementation, I added the another set_rams function by the overloading, it looks like it would cause other targets broken. Eric's PR have fix this issue.

https://github.com/sifive/devicetree-overlay-generator/pull/41

**Comment by zongbox** [comment]
We are going the following PRs:
- https://github.com/sifive/freedom-e-sdk/pull/611
- https://github.com/sifive/freedom-devicetree-tools/pull/256

After those PRs are merged, we could move on here.

**Comment by paul-walmsley-sifive** [comment]
Hi @zongbox , I merged those two pull requests.  Looks like the submodules need to be updated

**Comment by zongbox** [comment]
Changed in v3:
 - Add segger libc fixup by @paul-walmsley-sifive 
 - Modify compatible of ccache and prci in dts of Unleashed
 - Update all exist BSP files apart from Unmatched.
 - Re-bumps submodules to include some fixes.

**Comment by nick-knight** [comment]
@zongbox Have the "segger" CI checks really been running for 5 days (!?)

**Comment by paul-walmsley-sifive** [comment]
> @zongbox Have the "segger" CI checks really been running for 5 days (!?)

Github Actions appears to just be confused.  This PR originated before we dropped the SEGGER checks out of the FESDK-public CI.  Even though they've now been removed (and the "Details" link no longer shows them), this main page still mentions them.

**Pull request merged**
