### PR TITLE
Fix .sdata section allocation

### PR DESCRIPTION
**Pull request by a0u**
This addresses the linker warning ``section `.sdata' can't be allocated in segment 1``, which results in `.sdata` being assigned the wrong LMA.  Moving `.init_array` and `.fini_array` sections to the flash segment (as they do not need to be writeable) appears to circumvent this.

### CODE REVIEW

**Comment by a0u** [comment]
@aswaterman Do you have any insight as to why `ld` was originally dissatisfied with `.sdata`?  Is it related to the memory region attributes in the linker script?

Problematic ELF header:
```
$ riscv32-unknown-elf-readelf -Sl MandlebrotTouch.ino.elf
There are 24 section headers, starting at offset 0x773d8:

Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            00000000 000000 000000 00      0   0  0
  [ 1] .init             PROGBITS        20400000 000098 000074 00  AX  0   0  1
  [ 2] .text             PROGBITS        20400074 00010c 007a50 00 WAX  0   0  4
  [ 3] .rodata           PROGBITS        20407ac8 007b60 0008e8 00   A  0   0  8
  [ 4] .eh_frame         PROGBITS        204083b0 008448 000028 00   A  0   0  4
  [ 5] .lalign           PROGBITS        204083d8 0088c4 000000 00   W  0   0  1
  [ 6] .dalign           PROGBITS        80000000 0088c4 000000 00   W  0   0  1
  [ 7] .init_array       INIT_ARRAY      80000000 008470 000014 04  WA  0   0  4
  [ 8] .data             PROGBITS        80000018 008484 000428 00  WA  0   0  8
  [ 9] .sdata            PROGBITS        80000440 0088ac 000018 00  WA  0   0  4
  [10] .bss              NOBITS          80000458 000000 000134 00  WA  0   0  4
  [11] .stack            NOBITS          80003800 000000 000800 00  WA  0   0  1
  [12] .debug_frame      PROGBITS        00000000 0088c4 00394c 00      0   0  4
  [13] .debug_info       PROGBITS        00000000 00c210 02f216 00      0   0  1
  [14] .debug_abbrev     PROGBITS        00000000 03b426 0080fd 00      0   0  1
  [15] .debug_loc        PROGBITS        00000000 043523 015c68 00      0   0  1
  [16] .debug_aranges    PROGBITS        00000000 059190 000c10 00      0   0  8
  [17] .debug_ranges     PROGBITS        00000000 059da0 002630 00      0   0  1
  [18] .debug_line       PROGBITS        00000000 05c3d0 013374 00      0   0  1
  [19] .debug_str        PROGBITS        00000000 06f744 005bf6 01  MS  0   0  1
  [20] .comment          PROGBITS        00000000 07533a 000011 01  MS  0   0  1
  [21] .symtab           SYMTAB          00000000 07534c 0010a0 10     22  90  4
  [22] .strtab           STRTAB          00000000 0763ec 000f0c 00      0   0  1
  [23] .shstrtab         STRTAB          00000000 0772f8 0000dd 00      0   0  1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  p (processor specific)

Elf file type is EXEC (Executable file)
Entry point 0x20400000
There are 3 program headers, starting at offset 52

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  LOAD           0x000098 0x20400000 0x20400000 0x083d8 0x083d8 RWE 0x8
  LOAD           0x008470 0x80000000 0x204083d8 0x00454 0x00454 RW  0x8
  NULL           0x000000 0x80000458 0x80000458 0x00000 0x00934 RW  0x4

 Section to Segment mapping:
  Segment Sections...
   00     .init .text .rodata .eh_frame
   01     .init_array .data
   02     .bss
```

**Comment by aswaterman** [comment]
Nope.  It is weird they were marked writable, though.  In any case, I'd just take the good fortune for granted...

**Comment by epall** [comment]
I'm pretty sure something deeper is wrong here. I'm porting contiki to HiFive1 and ran into the same linker error here using the "fixed" linker script. I hacked around it by adding a dummy section after .sdata so that .sdata does make it into the ram_init segment, but now it seems my symbols are off by 4 bytes.

**Comment by epall** [comment]
Huh. My problem went away when I dropped -export-dynamic from the linker flags.

**Pull request merged**
