### PR TITLE
The HiFive1 has a 128Mb flash

### PR DESCRIPTION
**Pull request by palmer-dabbelt**
The website says there's a 128Mb flash on the HiFive1, but the linker scripts say it's 512MB.

### CODE REVIEW

**Comment by mwachs5** [comment]
Half of that flash is actually used for the FPGA. So it should only be 8M if you are starting at 0x20400000.

**Comment by palmer-dabbelt** [comment]
The HiFive1 doesn't have an FPGA... :)

**Comment by mwachs5** [comment]
True. 
But this is still using the first 4MB then for the "safe bootloader" code. That's why it's starting at 0x20400000 instead of 0x2000_0000. So I guess the size is most accurately 12MB.

**Comment by ilg-ul** [comment]
>  first 4MB then for the "safe bootloader" code

a very useful feature, given how easy it is to brick the board. (while trying to do active development on the board, abruptly terminating openocd, like when canceling a debug session, most of the time leaves the board unusable, with openocd no longer able to connect to the board; the only solution I found was to bring the board in bootloader mode, and restart the debug session).

so, although techincally the Arduino bootloader is not mandatory for bare-metal development, it is highly recommended to preserve the bootloader, and have the application loader scripts skip the first 4 MiB, leaving only 12 MiB for the application.

**Comment by palmer-dabbelt** [comment]
Thanks, I updated it to 12MB

**Pull request closed without merging**
