### PR TITLE
Add TARGET as a synonym for BOARD

### PR DESCRIPTION
**Pull request by nategraff-sifive**

### CODE REVIEW

**Comment by sifivekevin** [comment]
Nate,

The local-interrupt example fails to build when I use TARGET=X, but works when I use BOARD=X, for any X

**Comment by sifivekevin** [comment]
I pulled the latest changes about 3 minutes ago and it still fails.
Another pull pulled nothing new just now.

**Comment by sifivekevin** [comment]
Wait. Let me do a little more testing.

**Comment by sifivekevin** [comment]
I take that back.  It does appear to be working with the latest change.  I
saw a different error, unrelated.

**Comment by sifivekevin** [comment]
Nate, I found another problem.   The "list-targets" is treated as an empty recipe and not a fall-through to the list-boards recipe.  This breaks the list-options target.  If I change list-targets to be:

list-targets: **list-boards**
list-boards:
    @echo bsp-list: $(sort $(filter-out $(EXCLUDE_TARGET_DIRS),$(notdir $(wildcard bsp/*))))

**Comment by sifivekevin** [comment]
Nate,  I'm also fine just eliminating the list-boards target (in favor of the list-targets target).  I don't think we need to worry about backward compatibility here since FS is the only known consumer of the target (and only in the last couple of days).

**Comment by nategraff-sifive** [comment]
@sifivekevin I removed list-boards

**Comment by sifivekevin** [comment]
Since this PR is not "sssigned" to anyone, does that mean I can do the merge and close it?

**Comment by bsousi5** [comment]
Please go ahead an merge, if you need to use the change.
I just took a look, and it is fine with me.

Bunnaroath

**Pull request merged**
